import "@/public/styles/globals.css";
import "@/public/styles/scroll-bar.css";
import "@/public/styles/github-corner.css";
import type { Metadata } from "next";
import { Footer } from "@/components/navigation/Footer";
import { Navbar } from "@/components/navigation/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-darkViolet">
        <Navbar />
        <main className="min-h-screen pt-20 md:p-20 bg-darkViolet text-cyan-50 bg-confetti bg-fixed">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
