import { Navbar } from "@/components/navigation/Navbar";
import "./styles/globals.css";
import "./styles/scroll-bar.css";
import "./styles/github-corner.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        <main className="min-h-screen p-20 bg-darkViolet text-cyan-50 bg-confetti bg-fixed">
          {children}
        </main>
      </body>
    </html>
  );
}
